const AccessControl = require('accesscontrol')
const ac = new AccessControl()

ac.grant('user')
    .readAny('authors')
    .createAny('authors')
    .updateAny('authors')
    .deleteAny('authors')
    .readAny('books')
    .createAny('books')
    .updateAny('books')
    .deleteAny('books')
    .readAny('students')
    .createAny('students')
    .updateAny('students')
    .deleteAny('students')
    .readAny('loans')
    .createAny('loans')
    .updateAny('loans')
    .deleteAny('loans')
    .updateAny('loanReturn')    
    .updateAny('changePassword')
    // .readAny('categoriesById')
    // .readAny('articlesById')
    // .readAny('articlesByCategory')

ac.grant('admin')
    .extend('user')
    .readAny('users')
    .createAny('users')
    .updateAny('users')
    .deleteAny('users')

    
module.exports = ac